version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: attendance_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: attendance_db
    ports:
      - "5443:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: attendance_backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: admin234
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: attendance_db

  employee-attendance:
    build: ./Employee-attendance
    container_name: employee_attendance_ui
    ports:
      - "8018:80"
    depends_on:
      - backend

  hr-attendance:
    build: ./HR-attendance
    container_name: hr_attendance_ui
    ports:
      - "8019:80"
    depends_on:
      - backend

volumes:
  postgres_data:

