version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: attendance-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: attendance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1023
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./Backend
    container_name: attendance-backend
    ports:
      - "3002:3002"
    depends_on:
      - postgres

  employee-attendance:
    build:
      context: ./Employee-attendance
    container_name: employee-attendance
    ports:
      - "8003:80"
    depends_on:
      - backend

  hr-attendance:
    build:
      context: ./HR-attendance
    container_name: hr-attendance
    ports:
      - "8004:80"
    depends_on:
      - backend

volumes:
  pgdata:

